name: Despliegue

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v2

      - name: Despliegue
        uses: easingthemes/ssh-deploy@v2.1.2
        with:
          sshPrivateKey: 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
          remoteHost: 143.198.114.252
          remoteUser: u215167
          remotePort: 22  # Puerto SSH, si es diferente al predeterminado
          sshCmdArgs: '-o StrictHostKeyChecking=no'  # Opcional, para omitir la verificación del fingerprint del host
          source: dist
          target: /path/to/destination
          args: '-p 1893470'  # Reemplaza 'PASSWORD' con la contraseña real del usuario del servidor
