name: Despliegue automático

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v2

      - name: Despliegue de la carpeta dist
        uses: easingthemes/ssh-deploy@main
        with:
          server: 143.198.114.252
          port: 22
          username: u215167
          password: 1893470
          local_path: dist/
          remote_path: /public_html/
