name: Despliegue

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v2

      - name: Despliegue
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: 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
          REMOTE_HOST: 143.198.114.252
          REMOTE_USER: u215167
          REMOTE_PORT: 22  # Puerto SSH, si es diferente al predeterminado
          SSH_CMD_ARGS: '-o StrictHostKeyChecking=no'  # Opcional, para omitir la verificación del fingerprint del host
          SOURCE: dist/
          TARGET: public_html/
          ARGS: '-p 1893470'  # Reemplaza 'PASSWORD' con la contraseña real del usuario del servidor
